apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=teknikhub/gitlab
    argocd-image-updater.argoproj.io/myapp.update-strategy: latest
    argocd-image-updater.argoproj.io/myapp.allow-tags: regexp:^[0-9a-f]{8}$  # Sesuai dengan format SHA pendek (8 karakter)
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: teknikhub/gitlab:placeholder  # Akan di-update otomatis
